package net.marllex.waselak.core.network.dto

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class VendorResponse(
    val id: String,
    val name: String,
    @SerialName("logo_url") val logoUrl: String? = null,
    val address: String,
    @SerialName("contact_phone") val contactPhone: String,
    @SerialName("wallet_phone") val walletPhone: String? = null,
    @SerialName("default_delivery_fee") val defaultDeliveryFee: Double = 0.0,
    @SerialName("store_type") val storeType: String? = null,
    @SerialName("enable_tables") val enableTables: Boolean = true,
    @SerialName("enable_kds") val enableKds: Boolean = true,
    @SerialName("enable_dine_in") val enableDineIn: Boolean = true,
    @SerialName("enable_delivery") val enableDelivery: Boolean = true,
    @SerialName("enable_takeaway") val enableTakeaway: Boolean = true,
    @SerialName("enable_in_store") val enableInStore: Boolean = false,
    @SerialName("enable_pickup_later") val enablePickupLater: Boolean = false,
    @SerialName("business_type") val businessType: String = "RESTAURANT",
    @SerialName("tax_enabled") val taxEnabled: Boolean = false,
    @SerialName("default_tax_percent") val defaultTaxPercent: Double = 0.0,
    @SerialName("stock_mode") val stockMode: String = "NONE",
    @SerialName("offline_mode_enabled") val offlineModeEnabled: Boolean = false,
    @SerialName("biometric_required") val biometricRequired: Boolean = false,
    @SerialName("enable_offline_mode") val enableOfflineMode: Boolean = false,
    @SerialName("digital_menu_url") val digitalMenuUrl: String? = null,
    @SerialName("enable_digital_menu") val enableDigitalMenu: Boolean = true,
    @SerialName("enable_recipe") val enableRecipe: Boolean = true,
    @SerialName("enable_split_payment") val enableSplitPayment: Boolean = true,
    @SerialName("enable_cash_drawer") val enableCashDrawer: Boolean = true,
    @SerialName("enable_returns") val enableReturns: Boolean = true,
    @SerialName("enable_customer_credit") val enableCustomerCredit: Boolean = false,
    @SerialName("enable_installments") val enableInstallments: Boolean = false,
    @SerialName("enable_pre_orders") val enablePreOrders: Boolean = false,
    @SerialName("enable_scheduled_orders") val enableScheduledOrders: Boolean = false,
    @SerialName("enable_suppliers") val enableSuppliers: Boolean = true,
    @SerialName("enable_drug_interactions") val enableDrugInteractions: Boolean = false,
    @SerialName("enable_prescriptions") val enablePrescriptions: Boolean = false,
    @SerialName("enable_analytics") val enableAnalytics: Boolean = true,
    @SerialName("enable_announcements") val enableAnnouncements: Boolean = true,
    @SerialName("enable_stock") val enableStock: Boolean = true,
    @SerialName("enable_attendance") val enableAttendance: Boolean = true,
    @SerialName("enable_overtime") val enableOvertime: Boolean = false,
    @SerialName("enable_salary") val enableSalary: Boolean = false,
    @SerialName("enable_customers") val enableCustomers: Boolean = true,
    @SerialName("enable_export") val enableExport: Boolean = true,
    @SerialName("enable_digital_receipt") val enableDigitalReceipt: Boolean = false,
    @SerialName("enable_whatsapp_receipt") val enableWhatsappReceipt: Boolean = false,
    @SerialName("enable_worker_qrcode") val enableWorkerQrcode: Boolean = false,
    @SerialName("enable_loyalty") val enableLoyalty: Boolean = false,
    @SerialName("enable_manual_discount") val enableManualDiscount: Boolean = true,
    @SerialName("enable_offers") val enableOffers: Boolean = true,
    @SerialName("loyalty_enabled") val loyaltyEnabled: Boolean = false,
    @SerialName("points_earn_rate") val pointsEarnRate: Double = 1.0,
    @SerialName("points_redeem_rate") val pointsRedeemRate: Double = 0.1,
    @SerialName("min_points_redeem") val minPointsRedeem: Int = 100,
    @SerialName("max_manual_discount_percent") val maxManualDiscountPercent: Double = 100.0,
    @SerialName("manual_discount_requires_pin") val manualDiscountRequiresPin: Boolean = false,
    @SerialName("facebook_url") val facebookUrl: String? = null,
    @SerialName("landing_page_url") val landingPageUrl: String? = null,
    @SerialName("instagram_url") val instagramUrl: String? = null,
    @SerialName("whatsapp_number") val whatsappNumber: String? = null,
    @SerialName("created_at") val createdAt: Long,
    @SerialName("updated_at") val updatedAt: Long? = null
)

@Serializable
data class UpdateVendorRequest(
    val name: String? = null,
    @SerialName("logo_url") val logoUrl: String? = null,
    val address: String? = null,
    @SerialName("contact_phone") val contactPhone: String? = null,
    @SerialName("wallet_phone") val walletPhone: String? = null,
    @SerialName("default_delivery_fee") val defaultDeliveryFee: Double? = null,
    @SerialName("store_type") val storeType: String? = null,
    @SerialName("enable_tables") val enableTables: Boolean? = null,
    @SerialName("enable_kds") val enableKds: Boolean? = null,
    @SerialName("enable_dine_in") val enableDineIn: Boolean? = null,
    @SerialName("enable_delivery") val enableDelivery: Boolean? = null,
    @SerialName("enable_takeaway") val enableTakeaway: Boolean? = null,
    @SerialName("enable_in_store") val enableInStore: Boolean? = null,
    @SerialName("enable_pickup_later") val enablePickupLater: Boolean? = null,
    @SerialName("business_type") val businessType: String? = null,
    @SerialName("tax_enabled") val taxEnabled: Boolean? = null,
    @SerialName("default_tax_percent") val defaultTaxPercent: Double? = null,
    @SerialName("stock_mode") val stockMode: String? = null,
    @SerialName("biometric_required") val biometricRequired: Boolean? = null,
    @SerialName("enable_offline_mode") val enableOfflineMode: Boolean? = null,
    @SerialName("enable_digital_menu") val enableDigitalMenu: Boolean? = null,
    @SerialName("enable_recipe") val enableRecipe: Boolean? = null,
    @SerialName("enable_split_payment") val enableSplitPayment: Boolean? = null,
    @SerialName("enable_cash_drawer") val enableCashDrawer: Boolean? = null,
    @SerialName("enable_returns") val enableReturns: Boolean? = null,
    @SerialName("enable_customer_credit") val enableCustomerCredit: Boolean? = null,
    @SerialName("enable_installments") val enableInstallments: Boolean? = null,
    @SerialName("enable_pre_orders") val enablePreOrders: Boolean? = null,
    @SerialName("enable_scheduled_orders") val enableScheduledOrders: Boolean? = null,
    @SerialName("enable_suppliers") val enableSuppliers: Boolean? = null,
    @SerialName("enable_drug_interactions") val enableDrugInteractions: Boolean? = null,
    @SerialName("enable_prescriptions") val enablePrescriptions: Boolean? = null,
    @SerialName("enable_analytics") val enableAnalytics: Boolean? = null,
    @SerialName("enable_announcements") val enableAnnouncements: Boolean? = null,
    @SerialName("enable_stock") val enableStock: Boolean? = null,
    @SerialName("enable_attendance") val enableAttendance: Boolean? = null,
    @SerialName("enable_overtime") val enableOvertime: Boolean? = null,
    @SerialName("enable_salary") val enableSalary: Boolean? = null,
    @SerialName("enable_customers") val enableCustomers: Boolean? = null,
    @SerialName("enable_export") val enableExport: Boolean? = null,
    @SerialName("enable_digital_receipt") val enableDigitalReceipt: Boolean? = null,
    @SerialName("enable_worker_qrcode") val enableWorkerQrcode: Boolean? = null,
    @SerialName("enable_loyalty") val enableLoyalty: Boolean? = null,
    @SerialName("enable_manual_discount") val enableManualDiscount: Boolean? = null,
    @SerialName("enable_offers") val enableOffers: Boolean? = null,
    @SerialName("loyalty_enabled") val loyaltyEnabled: Boolean? = null,
    @SerialName("points_earn_rate") val pointsEarnRate: Double? = null,
    @SerialName("points_redeem_rate") val pointsRedeemRate: Double? = null,
    @SerialName("min_points_redeem") val minPointsRedeem: Int? = null,
    @SerialName("max_manual_discount_percent") val maxManualDiscountPercent: Double? = null,
    @SerialName("manual_discount_requires_pin") val manualDiscountRequiresPin: Boolean? = null,
    @SerialName("facebook_url") val facebookUrl: String? = null,
    @SerialName("landing_page_url") val landingPageUrl: String? = null,
    @SerialName("instagram_url") val instagramUrl: String? = null,
    @SerialName("whatsapp_number") val whatsappNumber: String? = null,
)

@Serializable
data class PlanFeaturesResponse(
    @SerialName("plan_name") val planName: String,
    @SerialName("plan_display_name") val planDisplayName: String,
    @SerialName("price_egp") val priceEgp: Int,
    val features: PlanFeaturesDto,
    val limits: PlanLimitsDto,
    val usage: PlanUsageDto,
)

@Serializable
data class PlanFeaturesDto(
    @SerialName("stock_management") val stockManagement: Boolean,
    @SerialName("worker_attendance") val workerAttendance: Boolean,
    val overtime: Boolean,
    val salaries: Boolean,
    @SerialName("delivery_module") val deliveryModule: Boolean,
    @SerialName("customer_management") val customerManagement: Boolean,
    @SerialName("table_management") val tableManagement: Boolean = false,
    @SerialName("digital_receipt") val digitalReceipt: Boolean = false,
    @SerialName("worker_qrcode") val workerQrcode: Boolean = false,
    @SerialName("loyalty_points") val loyaltyPoints: Boolean = false,
    @SerialName("manual_discount") val manualDiscount: Boolean = false,
    @SerialName("offers_management") val offersManagement: Boolean = false,
    val analytics: String,
    @SerialName("digital_menu") val digitalMenu: String,
)

@Serializable
data class PlanLimitsDto(
    @SerialName("max_managers") val maxManagers: Int,
    @SerialName("max_cashiers") val maxCashiers: Int,
    @SerialName("max_delivery") val maxDelivery: Int,
    @SerialName("max_orders_per_month") val maxOrdersPerMonth: Int,
    @SerialName("max_menu_items") val maxMenuItems: Int,
    @SerialName("max_branches") val maxBranches: Int,
)

@Serializable
data class PlanUsageDto(
    val managers: Int,
    val cashiers: Int,
    val delivery: Int,
    @SerialName("monthly_orders") val monthlyOrders: Int,
    @SerialName("menu_items") val menuItems: Int,
)

@Serializable
data class PlanSummaryDto(
    val name: String,
    @SerialName("display_name") val displayName: String,
    @SerialName("price_egp") val priceEgp: Int,
    val features: PlanFeaturesDto,
    val limits: PlanLimitsDto,
)
