package net.marllex.waselak.core.model

import kotlinx.serialization.Serializable

@Serializable
data class Vendor(
    val id: String,
    val name: String,
    val logoUrl: String? = null,
    val address: String,
    val contactPhone: String,
    val walletPhone: String? = null,
    val defaultDeliveryFee: Double = 0.0,
    val storeType: String? = null,
    val enableTables: Boolean = true,
    val enableKds: Boolean = true,
    val enableDineIn: Boolean = true,
    val enableDelivery: Boolean = true,
    val enableTakeaway: Boolean = true,
    val enableInStore: Boolean = false,
    val enablePickupLater: Boolean = false,
    val businessType: String = "RESTAURANT",
    val taxEnabled: Boolean = false,
    val defaultTaxPercent: Double = 0.0,
    val stockMode: String = "NONE",
    val offlineModeEnabled: Boolean = false,
    val biometricRequired: Boolean = false,
    val enableOfflineMode: Boolean = false,
    val digitalMenuUrl: String? = null,
    val enableDigitalMenu: Boolean = true,
    val enableRecipe: Boolean = true,
    val enableSplitPayment: Boolean = true,
    val enableCashDrawer: Boolean = true,
    val enableReturns: Boolean = true,
    val enableCustomerCredit: Boolean = false,
    val enablePreOrders: Boolean = false,
    val enableScheduledOrders: Boolean = false,
    val enableSuppliers: Boolean = true,
    val enableDrugInteractions: Boolean = false,
    val enablePrescriptions: Boolean = false,
    val enableAnalytics: Boolean = true,
    val enableAnnouncements: Boolean = true,
    val loyaltyEnabled: Boolean = false,
    val pointsEarnRate: Double = 1.0,
    val pointsRedeemRate: Double = 0.1,
    val minPointsRedeem: Int = 100,
    val maxManualDiscountPercent: Double = 100.0,
    val manualDiscountRequiresPin: Boolean = false,
    val facebookUrl: String? = null,
    val landingPageUrl: String? = null,
    val instagramUrl: String? = null,
    val whatsappNumber: String? = null,
    val createdAt: Long,
    val updatedAt: Long? = null
)
